### ISSUE TITLE
[Feature Request] HMS Code Mappings

### ISSUE THREAD

**Issue by WolfwithSword** [aequasi/node-bambu#1]
Sometimes error or warning messages can appear during a print, and "most" of these are created with HMS codes that are in an unrecognizable format in MQTT.

Should be noted that HMS codes are not always errors, some will come up with no code at all, some are just messages and not errors, and some with codes do not have an associated wiki page yet.

In order to get a useful code and direct link to the wiki for a given HMS error, you can employ the following:

```js
function DecimalHexTwosComplement(decimal) {
    var size = 8;
    var hexadecimal;
    if (decimal >= 0) {
        hexadecimal = decimal.toString(16);

        while ((hexadecimal.length % size) != 0) {
            hexadecimal = "" + 0 + hexadecimal;
        }

        return hexadecimal;
    } else {
        hexadecimal = Math.abs(decimal).toString(16);
        while ((hexadecimal.length % size) != 0) {
            hexadecimal = "" + 0 + hexadecimal;
        }

        var output = '';
        for (var i = 0; i < hexadecimal.length; i++) {
            output += (0x0F - parseInt(hexadecimal[i], 16)).toString(16);
        }

        output = (0x01 + parseInt(output, 16)).toString(16);
        return output;
    }
}

// "hms" property of "print" in the MQTT message
let template = []
if(print.hms != undefined){
    for (var hms_code of print.hms) {
        var attr = DecimalHexTwosComplement(hms_code.attr);
        var code = DecimalHexTwosComplement(hms_code.code);
        let full_code = (attr + code).replace(/(.{4})/g, "$1_");
        full_code = full_code.substring(0, full_code.length - 1);
        let url = "https://wiki.bambulab.com/en/x1/troubleshooting/hmscode/"+full_code;
        template.push({"code": "HMS_"+full_code, "url": url, "description":""});
    }
    print.hms = template;
}
```

It retains it as an array, but changes the codes to be an object containing the HMS_\<code> and a url. Description is empty but you could fill the in manually if desired for common issues. Feel free to modify as much as you need, just easy to follow the logic here, taken (mostly) from my NodeRed functions.

The list of all hms codes that can come from this are here: https://wiki.bambulab.com/en/x1/troubleshooting/hmscode 
and the url's created will point to a specific code's page from here.

Could be useful to when a "new" HMS code pops up, to send a status message of it with a link to the page. Not sure if you would want to manually code in a few names/descriptions for common ones, or to let the links embed with the bot so it's "already handled" for you. And if one is removed you could send a messaged with "resolved X" perhaps, up to you!

**Comment by cryptiklemur** [comment]
Added in https://github.com/aequasi/node-bambu/releases/tag/0.2.0
